python3 -m nmt.nmt \
 --src=vi --tgt=en  \
 --embed_prefix=/home/karen/workspace/nmt/GloVe/vectors_300d \
 --vocab_prefix=/home/karen/workspace/nmt/webnlg/nmt_data/nmt_data/vocab   \
 --train_prefix=/home/karen/workspace/nmt/webnlg/nmt_data/nmt_data/train   \
 --dev_prefix=/home/karen/workspace/nmt/webnlg/nmt_data/nmt_data/dev    \
 --test_prefix=/home/karen/workspace/nmt/webnlg/nmt_data/nmt_data/test  \
 --out_dir=gnmt_adam_residual   \
 --num_train_steps=20000   \
 --steps_per_stats=100   \
 --num_layers=5   \
 --num_units=256  \
 --dropout=0.2   \
 --metrics=bleu  \
 --encoder_type=gnmt \
 --attention_architecture=gnmt_v2 \
 --optimizer=adam \
 --learning_rate=0.001 \
 --decay_scheme=luong5 \
 --attention=scaled_luong \
 --residual=True
